catalogMode: prefer
shellEmulator: true
packages:
  - playground
  - packages/**

catalogs:
  # Build & Dev Tools
  build:
    tsdown: ^0.20.1
    typescript: ^5.9.3
    unbuild: ^3.6.1

  # Documentation
  docs:
    vitepress: ^1.6.4

  # Git Hooks & Release
  git:
    bumpp: ^10.4.0
    simple-git-hooks: ^2.13.1

  # Linting & Formatting
  lint:
    '@antfu/eslint-config': ^7.2.0
    eslint: ^9.39.2
    eslint-import-resolver-node: ^0.3.9
    lint-staged: ^16.2.7

  # Testing
  test:
    vitest: ^4.0.18

  # Type Definitions
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^25.1.0
    '@types/postcss-js': ^4.1.0

  # UnoCSS Core & Presets
  unocss:
    '@unocss/core': ^66.6.0
    '@unocss/eslint-plugin': ^66.6.0
    '@unocss/preset-attributify': ^66.6.0
    '@unocss/preset-icons': ^66.6.0
    '@unocss/preset-legacy-compat': ^66.6.0
    '@unocss/preset-mini': ^66.6.0
    '@unocss/preset-rem-to-px': ^66.6.0
    '@unocss/preset-tagify': ^66.6.0
    '@unocss/preset-typography': ^66.6.0
    '@unocss/preset-web-fonts': ^66.6.0
    '@unocss/preset-wind3': ^66.6.0
    '@unocss/preset-wind4': ^66.6.0
    '@unocss/transformer-compile-class': ^66.6.0
    '@unocss/transformer-directives': ^66.6.0
    '@unocss/transformer-variant-group': ^66.6.0
    unocss: ^66.6.0
    unocss-preset-magicss: ^1.0.1

  # Utilities
  utils:
    '@babel/types': ^7.28.6
    esno: ^4.8.0
    execa: ^9.6.1
    fs-extra: ^11.3.3
    postcss: ^8.5.6
    postcss-js: ^5.0.3
    taze: ^19.9.2

  # Vue & Vite
  vue:
    '@vitejs/plugin-vue': ^6.0.3
    vite: ^7.3.1
    vue: ^3.5.27
    vue-tsc: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
